services:
  db:
    image: postgres:15
    restart: always # makes sure that container restarts if it is crashed
    container_name: leetboard_db
    environment:
      POSTGRES_DB: leetboard
      POSTGRES_USER: leetuser
      POSTGRES_PASSWORD: leetpass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./logging:/logging
      - ./static:/static
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leetuser -d leetboard"]
      interval: 5s
      timeout: 5s
      retries: 3 

  app:
    build:
      context: . #build from everything in the current directory (1337b04rd)
    container_name: leetboard_app
    ports:
      - "${PORT:-8080}:8080"
    environment:
      PORT: ${PORT}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: leetuser
      DB_PASSWORD: leetpass
      DB_NAME: leetboard
      UPLOAD_DIR: /data
      LOG_FILE_PATH: logging/logging.log
      SESSION_COOKIE_NAME: session_id
      SESSION_DURATION_DAYS: 7
      AVATAR_API_BASE_URL: https://rickandmortyapi.com/api/character
    volumes:
      - ./data:/data
      - ./logging:/logging
      - ./static:/static
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  pgdata: