# Work on this later
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: leetboard_db
    restart: always
    environment:
      POSTGRES_USER: leetuser
      POSTGRES_PASSWORD: leetpass
      POSTGRES_DB: leetboard
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leetboard_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: leetuser
      DB_PASSWORD: leetpass
      DB_NAME: leetboard
    command: ["./leetboard", "--port", "8080"]

volumes:
  pgdata:
