# Work on this later
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: leetboard_db
    environment:
      POSTGRES_DB: leetboard
      POSTGRES_USER: leetuser
      POSTGRES_PASSWORD: leetpass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always # makes sure that container restarts if it is crashed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leetuser"]
      interval: 5s
      timeout: 5s
      retries: 3 
    ports:
      - "5432:5432"

  app:
    # specify image?
    build: #why?
      context: .
    container_name: leetboard_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: leetuser
      DB_PASSWORD: leetpass
      DB_NAME: leetboard
    depends_on:
      db:
        condition: service_healthy
    command: ["./1337b04rd", "--port", "8080"]
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/"]  
      interval: 5s
      timeout: 5s
      retries: 3 

volumes:
  pgdata:
